trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: |
     mkdir build & cd build
     cmake -A x64 ..
     call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
     cmake --build . -- /p:Configuration=Release
  displayName: 'build QPanda on Windows vm'

- job: Macos
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
     mkdir build 
     cd build
     cmake  ..
     make 
  displayName: 'make QPanda2 available on mac os vm'



